DOMAIN-SUFFIX,pinduoduo.com,REJECT-DROP
DOMAIN-SUFFIX,sixi.com,REJECT-DROP
DOMAIN-SUFFIX,hellobike.com,DIRECT
DOMAIN-SUFFIX,alibabadns.com,DIRECT
DOMAIN-SUFFIX,caiyunapp.com,DIRECT
DOMAIN-SUFFIX,adsrvr.org,DIRECT
DOMAIN-SUFFIX,qtlcdn.com,DIRECT
DOMAIN-SUFFIX,zohocdn.com,DIRECT
DOMAIN-SUFFIX,airvisual.com,DIRECT
DOMAIN-SUFFIX,manmanbuy.com,DIRECT
DOMAIN-SUFFIX,ampaeservices.com,DIRECT
DOMAIN-SUFFIX,scmttec.com,DIRECT
DOMAIN-KEYWORD,icloud,DIRECT
DOMAIN-KEYWORD,apple,DIRECT
